### ISSUE TITLE
支持ftrl优化器

### ISSUE THREAD

**Issue by zhangys-lucky** [Qihoo360/tensornet#13]

**Comment by yaooolei** [comment]
@zhangys-lucky   pr-link: https://github.com/Qihoo360/tensornet/pull/24
wide_deep模型wide部分lr的优化器由ada_grad替换成ftrl，10天数据，训练和预测auc没有明显变化。
优化器超参设置：
batch_size = 64
wide_sparse_opt_lr = tn.core.AdaGrad(learning_rate=0.1, initial_g2sum=0.1, initial_scale=1e-3)
wide_sparse_opt_lr = tn.core.Ftrl(learning_rate=0.02, initial_range=0, beta=1, lambda1=0.1, lambda2=1)
